### ISSUE TITLE
Fix Highscores

### ISSUE THREAD

**Issue by maltfield** [nandanhere/kivySnake#1]
Hi,

Very nice to see this :)

The reason your kivy app crashes in Linux is because the AppImage is read-only

```
user@disp9246:~/Downloads$ wget --quiet https://github.com/nandanhere/cross-platform-python-gui/releases/download/1175176811_linux/helloWorld-linux-x86_64.1175176811.tar.bz2
user@disp9246:~/Downloads$ 

user@disp9246:~/Downloads$ tar -xf helloWorld-linux-x86_64.1175176811.tar.bz2
user@disp9246:~/Downloads$ dist/helloWorld.AppImage 
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_21-08-27_7.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.8 (default, Jul  4 2020, 10:00:57) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
[INFO   ] [Python      ] Interpreter at "/home/user/Downloads/dist/helloWorld.AppImage"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 18.3.6'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'llvmpipe (LLVM 7.0, 256 bits)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /tmp/.mount_helloWnCMYhB/opt/src/assets/ateadonut.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /tmp/.mount_helloWnCMYhB/opt/src/assets/atepoison.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /tmp/.mount_helloWnCMYhB/opt/src/assets/startgame.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /tmp/.mount_helloWnCMYhB/opt/src/assets/died.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /tmp/.mount_helloWnCMYhB/opt/src/assets/gotahighscore.wav: b"Audio device hasn't been opened"
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/tmp/.mount_helloWnCMYhB/opt/src/main.py", line 78, in <module>
     app.run()
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/tmp/.mount_helloWnCMYhB/opt/src/main.py", line 73, in build
     kv = Builder.load_file("main.kv")
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/lang/builder.py", line 306, in load_file
     return self.load_string(data, **kwargs)
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/lang/builder.py", line 410, in load_string
     rule_children=rule_children)
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
   File "/tmp/.mount_helloWnCMYhB/opt/src/main.py", line 53, in __init__
     store['HIGH_SCORE'] = {"HIGH_SCORE":1000}
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/storage/__init__.py", line 294, in __setitem__
     self.put(key, **values)
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/storage/__init__.py", line 180, in put
     self.store_sync()
   File "/tmp/.mount_helloWnCMYhB/opt/python3.7/lib/python3.7/site-packages/kivy/storage/jsonstore.py", line 51, in store_sync
     with open(self.filename, 'w') as fd:
 OSError: [Errno 30] Read-only file system: '/tmp/.mount_helloWnCMYhB/opt/src/scores.json'
user@disp9246:~/Downloads$ 
```

It actually runs fine if you extract the AppImage and run it in a rw filesystem

```
user@disp9246:~/Downloads$ cd dist/
user@disp9246:~/Downloads/dist$ 

user@disp9246:~/Downloads/dist$ ./helloWorld.AppImage --appimage-extract
user@disp9246:~/Downloads/dist$ squashfs-root/AppRun
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_21-08-27_9.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/user/Downloads/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.8 (default, Jul  4 2020, 10:00:57) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
[INFO   ] [Python      ] Interpreter at "/home/user/Downloads/dist/squashfs-root/opt/python3.7/bin/python3.7 /home/user/Downloads/dist/squashfs-root/opt/src/main.py"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 18.3.6'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'llvmpipe (LLVM 7.0, 256 bits)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/user/Downloads/dist/squashfs-root/opt/src/assets/ateadonut.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/user/Downloads/dist/squashfs-root/opt/src/assets/atepoison.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/user/Downloads/dist/squashfs-root/opt/src/assets/startgame.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/user/Downloads/dist/squashfs-root/opt/src/assets/died.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/user/Downloads/dist/squashfs-root/opt/src/assets/gotahighscore.wav: b"Audio device hasn't been opened"
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
```

It should work without crashing if you update your code to move the highscroes json file to somewhere on the filesystem outside the AppImage itself (eg the user's $HOME/.kivySnake)

**Comment by maltfield** [comment]
You could use 

```
os.path.join( os.path.expanduser('~') )
```

See also how I do this on all 3x OSes:

 * https://github.com/BusKill/buskill-app/blob/master/src/packages/buskill/__init__.py#L480-L521

**Comment by nandanhere** [comment]
thank you so much for the reply! i just need a simple location to store the file. ill try this out :)

**Comment by nandanhere** [comment]
It works really well! thank you so so much for the help!

**Comment by maltfield** [comment]
great :)

btw, if you'd like to be featured in the [in the wild](https://github.com/maltfield/cross-platform-python-gui#in-the-wild) section on the upstream repo, please:

1. change the about/description of this repo
1. change the app name from `helloWorld` to `kivySnake` or something
2. change the README.md to be specific to `kivySnake`

**Comment by nandanhere** [comment]
i edited the forked repo with the code in it. is that okay? I was planning on putting all the releases including the android one in nandanhere/kivysnake

**Comment by maltfield** [comment]
yeah that makes more sense. let me know when the merge is done and I'll check it out

**Comment by maltfield** [comment]
you can either merge the GitHub actions & build scripts into this repo or edit the one you forked. Just let me know when it's done, and I'll check it out.

I see you updated the README on the other repo, but not the app name (`helloWorld`) nor the repo description. it might make more sense to merge it into this repo, actually. Your choice.

**Comment by nandanhere** [comment]
I'm not exactly sure how to merge the repos ... i edited the forked repo accordingly 
i forgot to edit the title of the readme XD  but now i guess everything must be in order.. do let me know if i missed anything

**Comment by maltfield** [comment]
Changing the name from `helloWorld` is not obvious in all 3x builds, sorry. I did this recently for another fork, so just search for "helloWorld" in this diff to see where the changes need to be made:

 * https://github.com/maltfield/kivy-matrix-calculator/compare/6da6ac5cbebaa07ced995571d0cd68f9726ff28d..558694929394d7e1af47fb25624295b714bf0e62

**Comment by nandanhere** [comment]
I did the changes ! All should be well now :) i plan to document the process in the future and i will include these steps as well!

**Comment by maltfield** [comment]
awesome, I updated the repo's "Demo" sections to link to your fork :)

 * https://github.com/maltfield/cross-platform-python-gui

btw, if you ever have time and want to contribute-back, I'd love to add android directly to the CI pipeline, but I don't have time for it now.

I guess the first task would be to try to get the base `helloWorld` app to build to an apk somehow on the GitHub linux shared runner instance by adding some `android/buildApk.sh` script to the `build/` directory.

 * https://github.com/maltfield/cross-platform-python-gui/tree/master/build

And then adding a new section to the CI workflow yaml that executes this script in a GitHub linux shared runner on-push

 * https://github.com/maltfield/cross-platform-python-gui/blob/master/.github/workflows/build.yml

PRs are very welcome ;)
